services:
  mock:
    build: ./sl-linedata-mock
  service:
    build: ./transport-stop-counter-service
    ports:
      - "8080:8080"
  webapp:
    build: ./transport-stop-counter-webpage
    ports:
      - "3000:3000"
