---
logging:
  level: INFO
  loggers:
    se.david: DEBUG
backendUrl: http://mock
slKey: insert-some-key-here
jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true